apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: gos
    type: game-object
    app: villains
    version: base
  name: villains-base
spec:
  replicas: 0
  selector:
    matchLabels:
      app: villains
      version: base
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "9090"
      labels:
        project: gos
        type: game-object
        app: villains
        version: base
    spec:
      containers:
        - image:
          imagePullPolicy: Never
          name: villains
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          env:
            - name: METRICS_ENABLED
              value: "1"
            - name: TRACING_ENABLED
              value: "0"
            - name: AB_OFF
              value: "1"
            - name: JAVA_OPTIONS
              value: "-Dvertx.disableDnsResolver=true"
            - name: KAFKA_ADDRESS
              value: my-cluster-kafka-bootstrap.kafka:9092
            - name: WAVES_SIZE
              value: "10"
            - name: WAVES_DELAY
              value: "10"
            - name: WAVES_COUNT
              value: "2"
            - name: SPEED
              value: "70"
          securityContext:
            privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: villains
  labels:
    project: gos
    type: game-object
    app: villains
spec:
  ports:
    - name: http
      port: 8081
  selector:
    app: villains
